### ISSUE TITLE
missing FE Industry variables in reporting

### ISSUE THREAD

**Issue by orichters** [pik-piam/remind2#517] opened 2024-02-05 10:30 UTC
Dear colleagues,

remind2 buildLibrary complains that:
```
2. Test if REMIND reporting produces mandatory variables for NAVIGATE reporting ('test-piamInterfaces-NAVIGATE.R:26:5') - The following variables are expected in the piamInterfaces package,
          but cannot be found in the reporting generated:
 FE|Non-energy Use|Industry (EJ/yr),
 FE|w/o Non-energy Use|Industry (EJ/yr),
 FE|w/o Non-energy Use|Industry|Gases (EJ/yr),
 FE|w/o Non-energy Use|Industry|Liquids (EJ/yr),
 FE|w/o Non-energy Use|Industry|Solids (EJ/yr),
```

As for example `FE|w/o Non-energy Use|Industry|Solids` was [in the template already at least since Feb 2023](https://github.com/pik-piam/piamInterfaces/blob/871feff1822440283b72b6d558572b0fba2d4139/inst/templates/mapping_template_NAVIGATE.csv#L688), I suspect this is caused by a change in Industry FE reporting? Maybe @JakobBD or @mellamoSimon, do you have an idea?

**Comment by mellamoSimon** [comment] 2024-02-05 10:51
Hi Oli, 
Thank you for bringing this up. Does `vm_demFENonEnergySector` exist in the remind version that you used? it might be a problem of backward compatibility. I'll look into it :)

**Comment by orichters** [comment] 2024-02-05 10:55
For the test, a gdx file is downloaded: https://github.com/pik-piam/remind2/blob/master/tests/testthat/test-piamInterfaces-NAVIGATE.R#L8

This file is probably outdated, indeed.

@fbenke-pik might remember who gave him this file.

**Comment by mellamoSimon** [comment] 2024-02-05 11:23
ok, I will wait for that feedback. For the records, when `vm_demFENonEnergySector` (i.e., the flow of energy carriers used as feedstock in the chemical sector) does not exist, those variables (`FE|Non-energy Use|Industry (EJ/yr)`, etc.) are only calculated with an ad-hoc ex-post fix (by @fschreyer ) that was designed for the Ariadne project and is hidden behind a switch.

**Comment by orichters** [comment] 2024-02-05 11:25
But somehow before your change these variables were calculated for the gdx file in question, but now they aren't anymore. Is that something you can fix easily (maybe the switch can be adjusted)?

**Comment by fbenke-pik** [comment] 2024-02-05 11:30
> But somehow before your change these variables were calculated for the gdx file in question, but now they aren't anymore. Is that something you can fix easily (maybe the switch can be adjusted)?

Are you sure this was working before? I remember sth related to industry non-energy use that was never working, but we did not exclude it because it was supposed to be calculated eventually, once Simóns enhancements were merged.


I think I got the Navigate REMIND run in the gdx from Nico. As NAVIGATE is basically over and there are no new REMIND runs for this project (that is what I am assuming at least), just excluding these variables for this particular template might be the best solution. 

Whatever you decide. If you want me to use a new gdx for this check, just send it to me and i will replace it.

**Comment by mellamoSimon** [comment] 2024-02-05 11:31
>But somehow before your change these variables were calculated for the gdx file in question, but now they aren't anymore. Is that something you can fix easily (maybe the switch can be adjusted)?

sure, but the reported values will be very sketchy. I would argue that it's better not to report those variables if we don't really calculate them but sure.

**Comment by orichters** [comment] 2024-02-05 11:38
Ok, then I add to the NAVIGATE template that it should no expect these variables.

**Closed** 2024-02-05 11:44 UTC
